inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*

# We are not on ruby 2.3+ yet
Style/FrozenStringLiteralComment:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

# Enable when we are on ruby 2.5
Style/HashTransformKeys:
  Enabled: false

# Enable when we are on ruby 2.4
Style/HashTransformValues:
  Enabled: false

# Too restrictive
Metrics/ClassLength:
  Enabled: false

# Ignore RSpec methods - https://stackoverflow.com/a/41689335
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

# Enable when maximum line length is configured in the ‘Layout/LineLength` cop
Style/GuardClause:
  Enabled: false

# Enable when maximum line length is configured in the ‘Layout/LineLength` cop
Style/IfUnlessModifier:
  Enabled: false